"""add features_by_race

Revision ID: 17cb21c264fe
Revises: 30753f4b8a10
Create Date: 2026-05-25 22:19:28.104746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cb21c264fe'
down_revision: Union[str, Sequence[str], None] = '30753f4b8a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features_by_race',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_key', sa.Text(), nullable=False),
    sa.Column('driver_code', sa.Text(), nullable=False),
    sa.Column('driver_name', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('circuit_id', sa.Text(), nullable=False),
    sa.Column('feature_version', sa.Text(), nullable=False),
    sa.Column('avg_finish_last_5', sa.Float(), nullable=True),
    sa.Column('avg_quali_last_5', sa.Float(), nullable=True),
    sa.Column('podium_rate', sa.Float(), nullable=True),
    sa.Column('dnf_rate', sa.Float(), nullable=True),
    sa.Column('wet_weather_score', sa.Float(), nullable=True),
    sa.Column('teammate_delta', sa.Float(), nullable=True),
    sa.Column('tire_management_score', sa.Float(), nullable=True),
    sa.Column('constructor_form', sa.Float(), nullable=True),
    sa.Column('pitstop_avg', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('overtaking_difficulty', sa.Float(), nullable=True),
    sa.Column('tire_deg_factor', sa.Float(), nullable=True),
    sa.Column('safety_car_probability', sa.Float(), nullable=True),
    sa.Column('qualifying_position', sa.SmallInteger(), nullable=True),
    sa.Column('qualifying_delta_to_pole', sa.Float(), nullable=True),
    sa.Column('finish_position', sa.SmallInteger(), nullable=True),
    sa.Column('is_winner', sa.SmallInteger(), nullable=True),
    sa.Column('is_podium', sa.SmallInteger(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features_by_race')),
    sa.UniqueConstraint('race_key', 'driver_code', 'feature_version', name='features_race_driver_version_unique')
    )
    op.create_index('idx_features_driver_year', 'features_by_race', ['driver_code', 'year'], unique=False)
    op.create_index('idx_features_race_key', 'features_by_race', ['race_key'], unique=False)
    op.create_index('idx_features_version', 'features_by_race', ['feature_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_features_version', table_name='features_by_race')
    op.drop_index('idx_features_race_key', table_name='features_by_race')
    op.drop_index('idx_features_driver_year', table_name='features_by_race')
    op.drop_table('features_by_race')
    # ### end Alembic commands ###
