"""initial schema

Revision ID: 30753f4b8a10
Revises: 
Create Date: 2026-05-24 16:56:33.040065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30753f4b8a10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifying_raw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_key', sa.Text(), nullable=False),
    sa.Column('driver_code', sa.Text(), nullable=False),
    sa.Column('driver_id', sa.Text(), nullable=False),
    sa.Column('driver_name', sa.Text(), nullable=False),
    sa.Column('team', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('q1_time', sa.String(), nullable=True),
    sa.Column('q2_time', sa.String(), nullable=True),
    sa.Column('q3_time', sa.String(), nullable=True),
    sa.Column('best_lap_seconds', sa.Float(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('race_name', sa.Text(), nullable=False),
    sa.Column('circuit_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 20', name=op.f('ck_qualifying_raw_position')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifying_raw')),
    sa.UniqueConstraint('race_key', 'driver_code', name=op.f('uq_qualifying_raw_race_key'))
    )
    op.create_index(op.f('ix_qualifying_raw_driver_code'), 'qualifying_raw', ['driver_code', 'year'], unique=False)
    op.create_index(op.f('ix_qualifying_raw_race_key'), 'qualifying_raw', ['race_key'], unique=False)
    op.create_table('results_raw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_key', sa.Text(), nullable=False),
    sa.Column('driver_code', sa.Text(), nullable=False),
    sa.Column('driver_id', sa.Text(), nullable=False),
    sa.Column('driver_name', sa.Text(), nullable=False),
    sa.Column('team', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('grid_position', sa.SmallInteger(), nullable=False),
    sa.Column('finish_position', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('race_name', sa.Text(), nullable=False),
    sa.Column('circuit_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('finish_position BETWEEN 1 AND 20', name=op.f('ck_results_raw_finish_position')),
    sa.CheckConstraint('grid_position BETWEEN 0 AND 20', name=op.f('ck_results_raw_grid_position')),
    sa.CheckConstraint('points >= 0', name=op.f('ck_results_raw_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results_raw')),
    sa.UniqueConstraint('race_key', 'driver_code', name=op.f('uq_results_raw_race_key'))
    )
    op.create_index(op.f('ix_results_raw_driver_code'), 'results_raw', ['driver_code', 'year'], unique=False)
    op.create_index(op.f('ix_results_raw_race_key'), 'results_raw', ['race_key'], unique=False)
    op.create_table('telemetry_raw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('race_key', sa.Text(), nullable=False),
    sa.Column('driver_code', sa.Text(), nullable=False),
    sa.Column('lap_number', sa.SmallInteger(), nullable=False),
    sa.Column('lap_seconds', sa.Float(), nullable=True),
    sa.Column('stint', sa.SmallInteger(), nullable=False),
    sa.Column('compound', sa.String(), nullable=True),
    sa.Column('tyre_life', sa.Integer(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lap_number > 0', name=op.f('ck_telemetry_raw_lap_number')),
    sa.CheckConstraint('stint > 0', name=op.f('ck_telemetry_raw_stint')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_raw')),
    sa.UniqueConstraint('race_key', 'driver_code', 'lap_number', name=op.f('uq_telemetry_raw_race_key'))
    )
    op.create_index(op.f('ix_telemetry_raw_driver_code'), 'telemetry_raw', ['driver_code', 'year'], unique=False)
    op.create_index(op.f('ix_telemetry_raw_race_key'), 'telemetry_raw', ['race_key'], unique=False)
    op.create_table('validation_failures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_table', sa.Text(), nullable=False),
    sa.Column('race_key', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_failures'))
    )
    op.create_index('idx_validation_occurred_at', 'validation_failures', ['occurred_at'], unique=False)
    op.create_index('idx_validation_race_key', 'validation_failures', ['race_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_validation_race_key', table_name='validation_failures')
    op.drop_index('idx_validation_occurred_at', table_name='validation_failures')
    op.drop_table('validation_failures')
    op.drop_index(op.f('ix_telemetry_raw_race_key'), table_name='telemetry_raw')
    op.drop_index(op.f('ix_telemetry_raw_driver_code'), table_name='telemetry_raw')
    op.drop_table('telemetry_raw')
    op.drop_index(op.f('ix_results_raw_race_key'), table_name='results_raw')
    op.drop_index(op.f('ix_results_raw_driver_code'), table_name='results_raw')
    op.drop_table('results_raw')
    op.drop_index(op.f('ix_qualifying_raw_race_key'), table_name='qualifying_raw')
    op.drop_index(op.f('ix_qualifying_raw_driver_code'), table_name='qualifying_raw')
    op.drop_table('qualifying_raw')
    # ### end Alembic commands ###
